### ISSUE TITLE
All electric tools break upon hitting a mob [NeoForge 1.21.1]

### ISSUE THREAD

**Issue by ToasterPig** [Aurilisdev/Physica#322]
When hitting a mob with an electric tool of any charge the electric tool will instantly break. This includes the electric baton WHICH IS MEANT TO HIT MOBS. The only one that doesn't break upon hitting a mob is an uncharged chainsaw.

**Comment by skiprocks999** [comment]
Please comment on this thread if this continues on the latest update

**Comment by asnat2332** [comment]
I have the same problem. All power electric break at the first hit.

I have:
neoforge 21.1.1.174 (1.21.1)
voltaic-1.21.1-1.0.0-2
electrodynamics-1.21.1-0.10.1-1

**Comment by skiprocks999** [comment]
this should be addressed in the next update for Electro

**Comment by asnat2332** [comment]
I've run the tests now and the problem still remains.
I tried to craft each electric tool (drill, saw, baton) as I thought it would be different from the one I took from the creative menu, but it didn't work.

I know this is off topic, but during testing I found that a tool without energy does the same damage as a charged tool.

I have:
neoforge 21.1.1.174 (1.21.1)
voltaic-1.21.1-1.0.0-2
electrodynamics-1.21.1-0.10.1-2

**Comment by skiprocks999** [comment]
This should be corrected in the next release TM

**Comment by asnat2332** [comment]
Thanks for work. The error was fixed after installing 0.10.1-3.

I think this is no longer relevant to this topic, but an electric tool without energy does as much damage as a charged tool.

**Comment by skiprocks999** [comment]
that should have been resolved with the latest update as well. Was it not?

**Comment by asnat2332** [comment]
Tools no longer break at the first hit. That's right.
But an electric tool without energy does as much damage as a charged tool
I've tried taking a tool from the creative menu, tried crafting and tried discharging it, but the damage remains the same.
Can I then additionally send a video demonstrating the problem?

**Comment by skiprocks999** [comment]
Ah I see they moved damage to an attribute modifier. Will get this fixed

**Comment by skiprocks999** [comment]
This will be patched in the next update. I had to set up an event because this game is deteriorating by the day.

**Comment by asnat2332** [comment]
I tested the version: "electrodynamics-1.21.1-0.10.1-4"
The error has been fixed. Thanks for the work!
I think can close this topic.
